services:
  nginx:
    build:
      context: ./nginx/
    ports:
      - "80:80"
      - "443:443"
    env_file: .env
    volumes:
      - staticfiles:/app/staticfiles
    develop:
      watch:
        - path: ./nginx/
          action: rebuild
  website:
    build:
      context: ./website/
    command: yarn $YARN_SCRIPT -p $WEBSITE_PORT
    expose:
      - $WEBSITE_PORT
    develop:
      watch:
        - path: ./website/
          action: rebuild
  api:
    build:
      context: ./api/
    command: gunicorn api.wsgi:application --bind $API_HOST:$API_PORT
    expose:
      - $API_PORT
    env_file: .env
    volumes:
      - staticfiles:/app/staticfiles
      - ./api/db.sqlite3:/app/db.sqlite3
    develop:
      watch:
        - path: ./api/
          action: rebuild
volumes:
  staticfiles:
